apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'leaderboard-prod'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'prod'
  source:
    path: 'charts/leaderboard'
    repoURL: 'https://github.com/Snuffules/argocd-demo-leaderboard-qa-dev-helm'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
  project: 'default'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
